name: firebase_crud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  file_picker: ^6.1.1  
  csc_picker: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets :
    # - assets/my_icon.png
    - assets/images/placeholder.png
