// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAieVolrhK3F8wNpQMgkCdJ2Z1ri1_8VQ4',
    appId: '1:99990302568:web:bd854e84e3caf8ff9f70dd',
    messagingSenderId: '99990302568',
    projectId: 'fir-crud-9272f',
    authDomain: 'fir-crud-9272f.firebaseapp.com',
    storageBucket: 'fir-crud-9272f.appspot.com',
    measurementId: 'G-2EX2WYSPLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIJAPk_gIhMCi-vtjBYdL0AwQELUNljw',
    appId: '1:99990302568:android:5dd92c012f6ac7479f70dd',
    messagingSenderId: '99990302568',
    projectId: 'fir-crud-9272f',
    storageBucket: 'fir-crud-9272f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvazdMCloNJC46MhrwsS727NAuJNgd45I',
    appId: '1:99990302568:ios:aa43c29e9f815d849f70dd',
    messagingSenderId: '99990302568',
    projectId: 'fir-crud-9272f',
    storageBucket: 'fir-crud-9272f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvazdMCloNJC46MhrwsS727NAuJNgd45I',
    appId: '1:99990302568:ios:1bfa2731c768c4ed9f70dd',
    messagingSenderId: '99990302568',
    projectId: 'fir-crud-9272f',
    storageBucket: 'fir-crud-9272f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
